package io.kodium.core

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import org.kotlincrypto.hash.sha2.SHA256

/**
 * Encodes a byte array into a Base64-encoded string.
 *
 * @return a Base64-encoded string representation of the byte array
 */
@OptIn(ExperimentalEncodingApi::class)
fun ByteArray.encodeToBase64String(): String = Base64.encode(this)

/**
 * Decodes the current string, which is encoded in Base64 format, into a byte array.
 *
 * @throws IllegalArgumentException if the input string contains characters not valid in Base64 encoding.
 * @return A byte array representing the decoded data of the Base64-encoded string.
 */
@OptIn(ExperimentalEncodingApi::class)
fun String.decodeBase64(): ByteArray = Base64.decode(this)

private const val CHECKSUM_SIZE = 4

/**
 * Encodes the current byte array to a Base64-encoded string with an appended checksum. The checksum
 * is generated by applying a double SHA-256 hash to the byte array and then appending the first four
 * bytes of the result to the original array before encoding.
 *
 * @return A Base64-encoded string representation of the byte array with the checksum appended.
 */
@OptIn(ExperimentalEncodingApi::class)
fun ByteArray.encodeToBase64WithChecksum(): String = ByteArray(size + CHECKSUM_SIZE).apply {
    this@encodeToBase64WithChecksum.copyInto(this, 0, 0, this@encodeToBase64WithChecksum.size)
    val checksum = this@encodeToBase64WithChecksum.sha256().sha256()
    checksum.copyInto(this, this@encodeToBase64WithChecksum.size, 0, CHECKSUM_SIZE)
}.encodeToBase64String()

/**
 * Decodes a Base64-encoded string with a checksum validation. The method first decodes the Base64 string,
 * separates the checksum from the payload, computes the checksum of the payload, and verifies it against the
 * decoded checksum. If the checksum validation fails, an exception is thrown.
 *
 * @throws IllegalArgumentException if the input string is too short for containing a checksum or if
 * the checksum validation fails.
 * @return A byte array representing the decoded payload of the Base64-encoded string after verifying the checksum.
 */
@OptIn(ExperimentalEncodingApi::class)
fun String.decodeBase64WithChecksum(): ByteArray {
    val rawBytes = decodeBase64()
    if (rawBytes.size < CHECKSUM_SIZE) {
        throw IllegalArgumentException("Too short for checksum: $this")
    }
    val checksum = rawBytes.copyOfRange(rawBytes.size - CHECKSUM_SIZE, rawBytes.size)
    val payload = rawBytes.copyOfRange(0, rawBytes.size - CHECKSUM_SIZE)
    val hash = payload.sha256().sha256()
    val computedChecksum = hash.copyOfRange(0, CHECKSUM_SIZE)

    var match = 0
    for (i in checksum.indices) {
        match = match or (checksum[i].toInt() xor computedChecksum[i].toInt())
    }

    if (match == 0) {
        return payload
    } else {
        throw IllegalArgumentException("Checksum mismatch")
    }
}

/**
 * Computes the SHA-256 cryptographic hash of the current byte array.
 */
private fun ByteArray.sha256(): ByteArray = SHA256().digest(this)
