package io.kodium.core

import io.kodium.MlKemVariant
import io.kodium.core.fips203.DefaultRandomProvider
import io.kodium.core.fips203.KyberCipherText
import io.kodium.core.fips203.KyberConstants
import io.kodium.core.fips203.KyberDecapsulationKey
import io.kodium.core.fips203.KyberEncapsulationKey
import io.kodium.core.fips203.KyberKeyGenerator
import io.kodium.core.fips203.KyberParameter

/**
 * FIPS 203 ML-KEM-768 implementation wrapper for Kodium PQC Hybrid Architecture.
 *
 * Encapsulation and decapsulation follow the [MlKemVariant] of the key involved, so keys generated by
 * Kodium 1.0.0 ([MlKemVariant.LEGACY]) keep interoperating with 1.0.0 peers.
 */
object MLKEM {
    const val PublicKeySize = 1184 // ML-KEM-768
    const val SecretKeySize = 2400 // ML-KEM-768
    const val CiphertextSize = 1088 // ML-KEM-768
    const val SharedSecretSize = 32

    /**
     * Generates a FIPS 203 ML-KEM-768 key pair using a CSPRNG.
     *
     * @return The pair (public key, secret key).
     */
    fun keyPair(): Pair<ByteArray, ByteArray> = keyPair(MlKemVariant.FIPS_203)

    /**
     * Generates an ML-KEM-768 key pair of the given [variant] using a CSPRNG.
     *
     * Use [MlKemVariant.LEGACY] only for keys that peers still running Kodium 1.0.0 must encapsulate to.
     *
     * @return The pair (public key, secret key).
     */
    fun keyPair(variant: MlKemVariant): Pair<ByteArray, ByteArray> {
        val z = ByteArray(KyberConstants.N_BYTES).also { DefaultRandomProvider.fillWithRandom(it) }
        val d = ByteArray(KyberConstants.N_BYTES).also { DefaultRandomProvider.fillWithRandom(it) }
        val kp = KyberKeyGenerator.generate(KyberParameter.ML_KEM_768, z, d, variant)
        z.fill(0)
        return Pair(kp.encapsulationKey.fullBytes, kp.decapsulationKey.fullBytes)
    }

    /**
     * Encapsulates a shared secret using the recipient's public key.
     * Uses a CSPRNG for entropy, and the [MlKemVariant] of [publicKey].
     */
    fun encapsulate(publicKey: ByteArray): Pair<ByteArray, ByteArray> {
        require(publicKey.size == PublicKeySize) { "Invalid public key size" }
        val key = KyberEncapsulationKey.fromBytes(publicKey)
        val result = key.encapsulate()
        return Pair(result.sharedSecretKey, result.cipherText.fullBytes)
    }

    /**
     * Decapsulates the ciphertext using the secret key, following the [MlKemVariant] of [secretKey].
     */
    fun decapsulate(ciphertext: ByteArray, secretKey: ByteArray): ByteArray? {
        if (ciphertext.size != CiphertextSize || secretKey.size != SecretKeySize) return null

        return try {
            val key = KyberDecapsulationKey.fromBytes(secretKey)
            val ct = KyberCipherText.fromBytes(ciphertext)
            key.decapsulate(ct)
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Extracts the public key from the secret key (FIPS 203 specification).
     */
    fun getPublicKeyFromSecretKey(secretKey: ByteArray): ByteArray {
        require(secretKey.size == SecretKeySize) { "Invalid secret key size" }
        return secretKey.copyOfRange(1152, 1152 + PublicKeySize)
    }

    /**
     * Returns the [MlKemVariant] an ML-KEM-768 public key was generated with.
     */
    fun variantOf(publicKey: ByteArray): MlKemVariant {
        require(publicKey.size == PublicKeySize) { "Invalid public key size" }
        return KyberEncapsulationKey.fromBytes(publicKey).key.variant
    }
}
