package io.kodium.ratchet

import io.kodium.KodiumPrivateKey
import io.kodium.KodiumPublicKey
import io.kodium.core.nacl
import io.kodium.core.NaClLowLevel
import org.kotlincrypto.macs.hmac.sha2.HmacSHA256

/**
 * Internal cryptographic utility functions powering the Double Ratchet and X3DH implementations.
 * This object abstracts away the low-level Curve25519 and AEAD encryption mechanics.
 */
internal object RatchetUtils {

    /**
     * Performs an X25519 Diffie-Hellman key agreement between a private key and a public key.
     * 
     * This operation securely computes a shared secret that can only be generated by the owners
     * of the respective private keys corresponding to the involved public keys.
     *
     * @param mySecretKey Our 32-byte private Curve25519 key.
     * @param theirPublicKey Their 32-byte public Curve25519 key.
     * @return The 32-byte shared secret resulting from the scalar multiplication.
     * @throws IllegalStateException if the underlying Diffie-Hellman computation fails.
     * @throws IllegalArgumentException if the provided keys are not exactly 32 bytes.
     */
    fun dh(mySecretKey: ByteArray, theirPublicKey: ByteArray): ByteArray {
        require(mySecretKey.size == 32) { "Invalid secret key size" }
        require(theirPublicKey.size == 32) { "Invalid public key size" }

        val sharedSecret = ByteArray(32)
        val status = NaClLowLevel.crypto_scalarmult(sharedSecret, mySecretKey, theirPublicKey)
        if (status != 0) {
            throw IllegalStateException("Diffie-Hellman failed")
        }
        return sharedSecret
    }

    /**
     * Authenticated Encryption with Associated Data (AEAD) using XSalsa20 and Poly1305.
     * 
     * To comply with Double Ratchet specifications, this function takes a 32-byte Message Key (MK)
     * and expands it using HKDF into two distinct keys: an Encryption Key (EK) for the cipher and
     * a MAC Key (AK) for the Associated Data authenticator.
     *
     * The resulting payload structure is: `[24-byte Nonce][Ciphertext + Poly1305 MAC][32-byte HMAC-SHA256 MAC]`.
     *
     * @param mk The 32-byte Message Key generated by the symmetric sending chain.
     * @param plaintext The raw message data to be encrypted.
     * @param ad Associated Data (usually the Ratchet header) that must be authenticated but not encrypted.
     * @return A single byte array containing the nonce, ciphertext, and authenticators.
     */
    fun aeadEncrypt(mk: ByteArray, plaintext: ByteArray, ad: ByteArray): ByteArray {
        // Derive 64 bytes: 32 for EK, 32 for AK
        val derived = HKDF.deriveSecrets(
            salt = ByteArray(32) { 0 }, // Using zeros as salt for MK expansion
            ikm = mk,
            info = "KodiumRatchetAEAD".encodeToByteArray(),
            length = 64
        )
        val ek = derived.sliceArray(0 until 32)
        val ak = derived.sliceArray(32 until 64)

        // Generate a random 24-byte nonce for SecretBox
        val nonce = nacl.randomBytes(nacl.SecretBox.NonceSize)
        
        // Encrypt the plaintext. SecretBox automatically appends a Poly1305 MAC to the ciphertext.
        val secretBoxCipher = nacl.SecretBox.seal(plaintext, nonce, ek)
        val ciphertext = nonce + secretBoxCipher

        // Authenticate the AD and the ciphertext using HMAC-SHA256 with AK
        val hmac = HmacSHA256(ak)
        hmac.update(ad)
        hmac.update(ciphertext)
        val mac = hmac.doFinal()

        // Result is [ciphertext][mac]
        return ciphertext + mac
    }

    /**
     * Decrypts an AEAD payload generated by [aeadEncrypt].
     * 
     * This function performs a rigorous constant-time verification of the appended HMAC-SHA256
     * against the provided Associated Data before attempting to decrypt the underlying XSalsa20 cipher.
     *
     * @param mk The 32-byte Message Key generated by the symmetric receiving chain.
     * @param ciphertextWithMac The complete encrypted payload containing the nonce, cipher, and MAC.
     * @param ad The Associated Data (Ratchet header) that was expected to be authenticated alongside the message.
     * @return The decrypted plaintext as a byte array, or `null` if the MAC verification or decryption fails.
     */
    fun aeadDecrypt(mk: ByteArray, ciphertextWithMac: ByteArray, ad: ByteArray): ByteArray? {
        val macSize = 32 // HMAC-SHA256 is 32 bytes
        val minSize = nacl.SecretBox.NonceSize + nacl.SecretBox.MacSize + macSize
        if (ciphertextWithMac.size < minSize) return null

        // Derive EK and AK
        val derived = HKDF.deriveSecrets(
            salt = ByteArray(32) { 0 },
            ikm = mk,
            info = "KodiumRatchetAEAD".encodeToByteArray(),
            length = 64
        )
        val ek = derived.sliceArray(0 until 32)
        val ak = derived.sliceArray(32 until 64)

        val ciphertextLen = ciphertextWithMac.size - macSize
        val ciphertext = ciphertextWithMac.sliceArray(0 until ciphertextLen)
        val receivedMac = ciphertextWithMac.sliceArray(ciphertextLen until ciphertextWithMac.size)

        // Verify HMAC
        val hmac = HmacSHA256(ak)
        hmac.update(ad)
        hmac.update(ciphertext)
        val computedMac = hmac.doFinal()
        
        // Constant-time comparison
        var match = 0
        for (i in 0 until macSize) {
            match = match or (receivedMac[i].toInt() xor computedMac[i].toInt())
        }
        if (match != 0) return null

        // Decrypt using SecretBox
        val nonce = ciphertext.sliceArray(0 until nacl.SecretBox.NonceSize)
        val secretBoxCipher = ciphertext.sliceArray(nacl.SecretBox.NonceSize until ciphertext.size)
        
        return nacl.SecretBox.open(secretBoxCipher, nonce, ek)
    }

    /**
     * Helper to convert ByteArray to Hex string.
     */
    fun toHex(bytes: ByteArray): String = bytes.joinToString("") {
        it.toInt().and(0xff).toString(16).padStart(2, '0')
    }
}

internal class ByteWriter {
    private var bytes = ByteArray(1024)
    private var position = 0

    fun write(b: Byte) {
        ensureCapacity(1)
        bytes[position++] = b
    }

    fun write(b: ByteArray) {
        ensureCapacity(b.size)
        b.copyInto(bytes, position)
        position += b.size
    }

    fun writeInt(i: Int) {
        ensureCapacity(4)
        bytes[position++] = (i shr 24).toByte()
        bytes[position++] = (i shr 16).toByte()
        bytes[position++] = (i shr 8).toByte()
        bytes[position++] = i.toByte()
    }

    private fun ensureCapacity(size: Int) {
        if (position + size > bytes.size) {
            val newBytes = ByteArray(maxOf(bytes.size * 2, position + size))
            bytes.copyInto(newBytes)
            bytes = newBytes
        }
    }

    fun toByteArray(): ByteArray = bytes.sliceArray(0 until position)
}

internal class ByteReader(private val bytes: ByteArray) {
    private var position = 0

    fun readByte(): Byte {
        if (position >= bytes.size) throw IllegalStateException("EOF")
        return bytes[position++]
    }

    fun readBytes(size: Int): ByteArray {
        if (position + size > bytes.size) throw IllegalStateException("EOF")
        val result = bytes.sliceArray(position until position + size)
        position += size
        return result
    }

    fun readInt(): Int {
        if (position + 4 > bytes.size) throw IllegalStateException("EOF")
        val b1 = bytes[position++].toInt() and 0xFF
        val b2 = bytes[position++].toInt() and 0xFF
        val b3 = bytes[position++].toInt() and 0xFF
        val b4 = bytes[position++].toInt() and 0xFF
        return (b1 shl 24) or (b2 shl 16) or (b3 shl 8) or b4
    }
}
