package io.kodium

/**
 * The ML-KEM construction an ML-KEM key pair belongs to.
 *
 * Kodium 1.0.0 and earlier generated ML-KEM keys and encapsulations from truncated SHAKE output
 * (see [LEGACY]). From 1.1.0 on, Kodium implements FIPS 203 correctly ([FIPS_203]) and keeps the old
 * construction only so that keys, ciphertexts and sessions created by 1.0.0 continue to work.
 *
 * The variant is a property of the key pair and is recognised from the key material itself, so it is
 * never stored or transmitted: encapsulation follows the recipient's public key and decapsulation
 * follows the own private key. Callers only choose a variant when generating a new key pair.
 *
 * @see Kodium.pqc.generateKeyPair
 * @see KodiumPqcPublicKey.mlKemVariant
 */
enum class MlKemVariant {
    /**
     * ML-KEM as specified in NIST FIPS 203. Interoperable with every conformant implementation
     * (BouncyCastle, `@noble/post-quantum`, HSMs), and the default for new key pairs.
     *
     * Kodium 1.0.0 cannot encapsulate to a key of this variant: a 1.0.0 sender produces a ciphertext
     * that decapsulates to a different shared secret, so hybrid decryption, PQXDH and the PQ ratchet
     * fail. Only hand these keys to peers running Kodium 1.1.0 or later.
     */
    FIPS_203,

    /**
     * The non-conformant ML-KEM of Kodium 1.0.0 and earlier: the matrix `Â` is expanded from 32 bytes
     * of SHAKE128 output and the noise polynomials from 64 bytes of SHAKE256 output, the rest being
     * zero (issue #11). Keys of this variant do not have the post-quantum security of ML-KEM and do not
     * interoperate with other ML-KEM implementations.
     *
     * Every key generated by Kodium 1.0.0 is of this variant and keeps working unchanged, with both
     * 1.0.0 and current peers. Generate new keys of this variant only while peers that still run
     * Kodium 1.0.0 must be able to encrypt to them, and replace them once those peers are upgraded;
     * the classical X25519/Ed25519 half of a hybrid key is unaffected by this variant.
     */
    LEGACY,
}
